# ===================================================================
# Porsche Digital GmbH - Spring Cloud Config.
# ===================================================================

# Property used on app startup to check the config server status
configserver:
    name: Porsche Digital GmbH - Registry config server
    status: Connected to the JHipster Registry config server, using https://github.com/gruenewald/jhipster-registry-sample-config !

# Default JWT secret token (to be changed in production!)
jhipster:
    security:
        authentication:
            jwt:
                secret: my-secret-token-to-change-in-production

# Service Registry
eureka:
    client:
        service-url:
            defaultZone: https://admin:${jhipster.registry.password}@registry.apps.emea.vwapps.io/eureka/
